#!/bin/bash

# package info
shpkg_name="hydra"
shpkg_description="A passaword cracker tool support GUI (gtk)"
shpkg_version=9.2
shpkg_source=https://github.com/vanhauser-thc/thc-hydra/archive/refs/tags/v9.2.tar.gz
# package build and runtime dependencies
shpkg_build_depends="clang make"
shpkg_depends="openssl openssl-tool libssh sslscan libcap ncurses-utils libidn libcrypt libedit libpcreposix pcre libssh zlib wget gtk2 gtk3 libglade db"
# package source code
shpkg_source="https://github.com/vanhauser-thc/thc-hydra/archive/refs/tags/v9.2.tar.gz"

prepare(){
	cd ${SRCDIR}
	./configure --prefix=/data/data/com.termux/files/usr
}

build(){
	make
}

finish(){
	echo "Installing hydra and Xhydra"
	${SHPKG_SUDO} make install
}

remove(){
	${SHPKG_SUDO} rm -rf $PREFIX/bin/hydra
	${SHPKG_SUDO} rm -rf $PREFIX/share/applications/xhydra.desktop
	${SHPKG_SUDO} rm -rf $PREFIX/bin/xhydra
	${SHPKG_SUDO} rm -rf $PREFIX/bin/dpl4hydra.sh
        ${SHPKG_SUDO} rm -rf $PREFIX/bin/hydra-wizard.sh
        ${SHPKG_SUDO} rm -rf $PREFIX/bin/pw-inspector
        ${SHPKG_SUDO} rm -rf $PREFIX/etc/dpl4hydra_local.csv
        ${SHPKG_SUDO} rm -rf $PREFIX/etc/dpl4hydra_full.csv
        ${SHPKG_SUDO} rm -rf $PREFIX/man/man1/xhydra.1
        ${SHPKG_SUDO} rm -rf $PREFIX/man/man1/pw-inspector.1
        ${SHPKG_SUDO} rm -rf $PREFIX/man/man1/hydra.1
}
