#!/bin/bash

# package name
shpkg_name="file-roller"
shpkg_description="A archive manager for GNOME"
shpkg_version=3.40.0
shpkg_source=https://github.com/GNOME/file-roller
# package build and runtime dependencies
shpkg_build_depends="clang ninja cmake"
shpkg_depends="openssl gtk3 libnotify cpio libconfig json-glib libarchive glib unzip unrar bsdtar zip p7zip"

# package source code
shpkg_source="https://github.com/GNOME/file-roller/archive/refs/tags/3.40.0.tar.gz"

prepare(){
	pip install meson
	cd ${SRCDIR}
	meson --prefix=$PREFIX build
}

build(){
	ninja -C build
}

finish(){
	ninja install -C build
}

remove(){
	rm -rf $PREFIX/bin/file-roller
	rm -rf $PREFIX/share/applications/org.gnome.FileRoller.desktop
	rm -rf $PREFIX/libexec/file-roller/
	rm -rf $PREFIX/share/dbus-1/services/org.gnome.FileRoller.service
	rm -rf $PREFIX/share/dbus-1/services/org.gnome.ArchiveManager1.service
	rm -rf $PREFIX/share/metainfo/org.gnome.FileRoller.appdata.xml
	rm -rf $PREFIX/share/glib-2.0/schemas/org.gnome.FileRoller.gschema.xml
	rm -rf $PREFIX/share/file-roller
	rm -rf $PREFIX/share/icons/hicolor/scalable/apps/org.gnome.ArchiveManager.*
	rm -rf $PREFIX/share/icons/hicolor/symbolic/apps/org.gnome.ArchiveManager-symbolic.svg
}
