#!/bin/bash

# package info
shpkg_name="flat-remix-gtk-theme"
shpkg_description="Flat remix gtk theme for termux x11"
shpkg_version=git+a00332545430b19dae171e965becc36d98448e83
shpkg_source=https://github.com/daniruiz/flat-remix-gtk
# package build and runtime dependencies
shpkg_build_depends="make"
shpkg_depends="gtk2 gtk3"

# package source code
shpkg_source="https://github.com/daniruiz/flat-remix-gtk"

shpkg_src_use_git="true"

prepare(){
	 cd ${SRCDIR}
         mkdir -p $PREFIX/share/themes
}

build(){
	make
}

finish(){
	echo "Installing flat-remix-gtk-theme..."
	mv Flat-Remix-GTK-* $PREFIX/share/themes/
}

remove(){
	rm -rf $PREFIX/share/themes/Flat-Remix-GTK-*
}
